language: elixir

elixir:
  - 1.7.4
  - 1.8.1

otp_release:
  - 20.3
  - 21.3

env:
  global:
    - MIX_ENV=test

before_script:
  - mix do deps.get, deps.compile
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait MIX_ENV=test mix dialyzer --plt

script:
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.8"* ]]; then mix format --check-formatted ;fi
  - mix credo --strict
  - mix coveralls.travis

sudo: required

dist: trusty

cache:
  directories:
    - _build
    - deps
